-- Staging tables for M1 pipeline
-- Raw data loads before transformation and graph creation

-- Companies House company snapshot
DROP TABLE IF EXISTS stg_companies CASCADE;
CREATE TABLE stg_companies (
    company_name TEXT,
    company_number VARCHAR(20) PRIMARY KEY,
    reg_address_care_of TEXT,
    reg_address_po_box TEXT,
    reg_address_address_line_1 TEXT,
    reg_address_address_line_2 TEXT,
    reg_address_post_town TEXT,
    reg_address_county TEXT,
    reg_address_country TEXT,
    reg_address_post_code TEXT,
    company_category TEXT,
    company_status TEXT,
    country_of_origin TEXT,
    dissolution_date TEXT,
    incorporation_date TEXT,
    accounts_account_ref_day TEXT,
    accounts_account_ref_month TEXT,
    accounts_next_due_date TEXT,
    accounts_last_made_up_date TEXT,
    accounts_account_category TEXT,
    returns_next_due_date TEXT,
    returns_last_made_up_date TEXT,
    mortgages_num_mort_charges TEXT,
    mortgages_num_mort_outstanding TEXT,
    mortgages_num_mort_part_satisfied TEXT,
    mortgages_num_mort_satisfied TEXT,
    sic_code_sic_text_1 TEXT,
    sic_code_sic_text_2 TEXT,
    sic_code_sic_text_3 TEXT,
    sic_code_sic_text_4 TEXT,
    limited_partnerships_num_gen_partners TEXT,
    limited_partnerships_num_lim_partners TEXT,
    uri TEXT,
    previous_name_1_condate TEXT,
    previous_name_1_company_name TEXT,
    previous_name_2_condate TEXT,
    previous_name_2_company_name TEXT,
    previous_name_3_condate TEXT,
    previous_name_3_company_name TEXT,
    previous_name_4_condate TEXT,
    previous_name_4_company_name TEXT,
    previous_name_5_condate TEXT,
    previous_name_5_company_name TEXT,
    previous_name_6_condate TEXT,
    previous_name_6_company_name TEXT,
    previous_name_7_condate TEXT,
    previous_name_7_company_name TEXT,
    previous_name_8_condate TEXT,
    previous_name_8_company_name TEXT,
    previous_name_9_condate TEXT,
    previous_name_9_company_name TEXT,
    previous_name_10_condate TEXT,
    previous_name_10_company_name TEXT,
    conf_stmt_next_due_date TEXT,
    conf_stmt_last_made_up_date TEXT
);

-- Companies House PSC data (JSON format)
DROP TABLE IF EXISTS stg_psc CASCADE;
CREATE TABLE stg_psc (
    id SERIAL PRIMARY KEY,
    company_number VARCHAR(20) NOT NULL,
    raw_json JSONB NOT NULL
);

-- CCOD titles (UK companies owning property)
DROP TABLE IF EXISTS stg_ccod_titles CASCADE;
CREATE TABLE stg_ccod_titles (
    id SERIAL PRIMARY KEY,
    title_number VARCHAR(20) NOT NULL,
    tenure TEXT,
    property_address TEXT,
    district TEXT,
    county TEXT,
    region TEXT,
    postcode TEXT,
    multiple_address_indicator VARCHAR(1),
    price_paid TEXT,
    proprietor_name_1 TEXT,
    company_registration_no_1 TEXT,
    proprietorship_category_1 TEXT,
    proprietor_1_address_1 TEXT,
    proprietor_1_address_2 TEXT,
    proprietor_1_address_3 TEXT,
    proprietor_name_2 TEXT,
    company_registration_no_2 TEXT,
    proprietorship_category_2 TEXT,
    proprietor_2_address_1 TEXT,
    proprietor_2_address_2 TEXT,
    proprietor_2_address_3 TEXT,
    proprietor_name_3 TEXT,
    company_registration_no_3 TEXT,
    proprietorship_category_3 TEXT,
    proprietor_3_address_1 TEXT,
    proprietor_3_address_2 TEXT,
    proprietor_3_address_3 TEXT,
    proprietor_name_4 TEXT,
    company_registration_no_4 TEXT,
    proprietorship_category_4 TEXT,
    proprietor_4_address_1 TEXT,
    proprietor_4_address_2 TEXT,
    proprietor_4_address_3 TEXT,
    date_proprietor_added TEXT,
    additional_proprietor_indicator VARCHAR(1)
);

-- OCOD titles (Overseas companies owning property)
DROP TABLE IF EXISTS stg_ocod_titles CASCADE;
CREATE TABLE stg_ocod_titles (
    id SERIAL PRIMARY KEY,
    title_number VARCHAR(20) NOT NULL,
    tenure TEXT,
    property_address TEXT,
    district TEXT,
    county TEXT,
    region TEXT,
    postcode TEXT,
    multiple_address_indicator VARCHAR(1),
    price_paid TEXT,
    proprietor_name_1 TEXT,
    company_registration_no_1 TEXT,
    proprietorship_category_1 TEXT,
    country_incorporated_1 TEXT,
    proprietor_1_address_1 TEXT,
    proprietor_1_address_2 TEXT,
    proprietor_1_address_3 TEXT,
    proprietor_name_2 TEXT,
    company_registration_no_2 TEXT,
    proprietorship_category_2 TEXT,
    country_incorporated_2 TEXT,
    proprietor_2_address_1 TEXT,
    proprietor_2_address_2 TEXT,
    proprietor_2_address_3 TEXT,
    proprietor_name_3 TEXT,
    company_registration_no_3 TEXT,
    proprietorship_category_3 TEXT,
    country_incorporated_3 TEXT,
    proprietor_3_address_1 TEXT,
    proprietor_3_address_2 TEXT,
    proprietor_3_address_3 TEXT,
    proprietor_name_4 TEXT,
    company_registration_no_4 TEXT,
    proprietorship_category_4 TEXT,
    country_incorporated_4 TEXT,
    proprietor_4_address_1 TEXT,
    proprietor_4_address_2 TEXT,
    proprietor_4_address_3 TEXT,
    date_proprietor_added TEXT,
    additional_proprietor_indicator VARCHAR(1)
);

-- Add indexes after load completes
-- These will be added by stage_load.py after COPY operations